name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install pcap
      run: sudo apt install libpcap-dev

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ipxbox.go

  crosscompile:
    strategy:
      matrix:
        goarch: [386, amd64, arm64]
        goos: [darwin, freebsd, linux, windows]
        exclude:
        - goarch: 386
          goos: darwin

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        mkdir artifacts
        cd artifacts
        go build -tags nopcap -v ../ipxbox.go
        go build -tags nopcap -v ../standalone/ipxbox_uplink.go
      env:
        GOARCH: ${{ matrix.goarch }}
        GOOS: ${{ matrix.goos }}

    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        path: "artifacts"
        name: ipxbox_${{ matrix.goos }}_${{ matrix.goarch }}

